framework:
  secret: '%env(APP_SECRET)%'
  set_locale_from_accept_language: true
  csrf_protection:
    check_header: true
  router:
    utf8: true
  session:
    cookie_secure: auto
    cookie_samesite: lax
  rate_limiter:
    register:
      policy: fixed_window
      limit: 10
      interval: "1 hour"
    password_reset:
      policy: fixed_window
      limit: 5
      interval: "1 hour"

when@test:
  framework:
    test: true
